version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: hospital_db
    environment:
      POSTGRES_USER: hospital_user
      POSTGRES_PASSWORD: hospital_pass
      POSTGRES_DB: ayurvedic_hospital
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
